#!/bin/bash -e

# Copyright (C) 2014 Oliver Schulz <oliver.schulz@tu-dortmund.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.


EXEC_NAME=`basename "$0"`
GIT_BASE_PATH="$1"

if [ -z "${GIT_BASE_PATH}" ]  ; then
	echo "Syntax: ${EXEC_NAME} GIT_BASE_URL" 1>&2;
	echo "" 1>&2
	echo "Switches the remote origin (server) URL of a Git clone." 1>&2
	echo "" 1>&2
	echo "This tool assumes that the Git remote URL of your current local clone has the" 1>&2
	echo "format BASE_URL/PROJECT.git." 1>&2
	echo "" 1>&2
	echo "Examples:" 1>&2
	echo "    ${EXEC_NAME} git@github.com:GITHUB_USER" 1>&2
	echo "    ${EXEC_NAME} https://github.com/GITHUB_USER" 1>&2
	exit 1
fi

if ! git remote &> /dev/null ; then
	echo "ERROR: Not in an Git clone" 1>&2;
	exit 1
fi

CURRENT_REMOTE_URL=`git remote -v | grep '^origin[[:space:]].*[[:space:]](fetch)$' | sed 's/^origin\s\+\(.*\)\s\+(.*)$/\1/'`
echo "Current remote URL (remote \"origin\"): ${CURRENT_REMOTE_URL}"

if ! ( echo "${CURRENT_REMOTE_URL}" | grep -q '^.*/.*\.git$' ) ; then
	echo "ERROR: Can't handle format or current remote URL (remote \"origin\")." 1>&2;
	exit 1	
fi

REPO_NAME=`basename "${CURRENT_REMOTE_URL}"`

git remote set-url origin "${GIT_BASE_PATH}/${REPO_NAME}"

NEW_REMOTE_URL=`git remote -v | grep '^origin[[:space:]].*[[:space:]](fetch)$' | sed 's/^origin\s\+\(.*\)\s\+(.*)$/\1/'`
echo "New remote URL (remote \"origin\"): ${NEW_REMOTE_URL}"

echo ""
echo "Details:"
git remote show origin
